# Install Python dependencies, lint, run tests.

name: Contract-Alerts-Build

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, closed]
    paths:
      - search.py
      - test_search.py

permissions:
  contents: read

jobs:
  contract-alerts-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: pip package install
      run: |
        pip install . --use-pep517
        pip install flake8 pytest pytest-mock
    - name: Run python lint
      run: flake8 . --count --select=E9,F63,F7,F82 --ignore=F821 --show-source --statistics
    - name: Run pytest unit tests
      run: pytest test_search.py
    - name: Summary
      run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
